name: portel.nexgensis.com

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  packages: write
  contents: write
  pull-requests: read
  issues: read

jobs:
  backend:
    name: Backend
    uses: Nexgensis/github-actions/.github/workflows/docker-build.yml@main
    with:
      image: ghcr.io/nexgensis/webmanager-backend
      context: backend
      dockerfile: backend/Dockerfile
      push: true
      environment: Staging

  frontend:
    name: Frontend
    uses: Nexgensis/github-actions/.github/workflows/docker-build.yml@main
    with:
      image: ghcr.io/nexgensis/webmanager-frontend
      context: frontend
      dockerfile: frontend/Dockerfile
      push: true
      environment: Staging

  deploy:
    name: Deploy
    needs: [backend, frontend]
    uses: Nexgensis/github-actions/.github/workflows/deploy.yml@main
    with:
      cd_path: /root/webmanager
      image_tag: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'latest' }}
      environment: Staging
    secrets:
      host: ${{ secrets.DEMO_SERVER_IP }}
      ssh_key: ${{ secrets.SERVER_SSH_KEY }}
      username: root
