name: portel.nexgensis.com

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  packages: write
  contents: write
  pull-requests: read
  issues: read 

jobs:
  backend:
    name: Backend
    uses: Nexgensis/github-actions/.github/workflows/docker-build.yml@main
    with:
      image_name: webmanager-backend
      context: backend
      dockerfile: backend/Dockerfile
      branch: main
      environment: Staging

  frontend:
    name: Frontend
    uses: Nexgensis/github-actions/.github/workflows/docker-build.yml@main
    with:
      image_name: webmanager-frontend
      context: frontend
      dockerfile: frontend/Dockerfile
      branch: main
      environment: Staging

  deploy:
    name: Deploy
    needs: [backend, frontend]
    uses: Nexgensis/github-actions/.github/workflows/deploy.yml@main
    with:
      cd_path: /root/qms/ops-iq
      image_tag: latest
      environment: Staging
    secrets:
      host: ${{ secrets.DEMO_SERVER_IP }}
      ssh_key: ${{ secrets.SERVER_SSH_KEY }}
      username: root
  
  cleanup:
    needs: [deploy]
    uses: Nexgensis/github-actions/.github/workflows/cleanup-docker-images.yml@main
    with:
      environment: Staging
    secrets:
      host: ${{ secrets.DEMO_SERVER_IP }} 
      ssh_key: ${{ secrets.SERVER_SSH_KEY }}
      username: root
